import { ComponentLoader } from "adminjs";
import { getModelByName } from "@adminjs/prisma";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const componentLoader = new ComponentLoader();

const Components = {
  Dashboard: componentLoader.add("Dashboard", "./components/Dashboard"),
  CustomPanel: componentLoader.add("CustomPanel", "./components/CustomPanel"),
};

const dashboardHandler = async () => {
  const statusCountsData = await prisma.visa_applications.groupBy({
    by: ["status"],
    _count: {
      status: true,
    },
  });
  const dateVolumeData = await prisma.visa_applications.groupBy({
    by: ["application_date"],
    _count: {
      application_id: true,
    },
    orderBy: {
      application_date: "desc", // Order by date in descending order to get the latest dates first
    },
  });
  if (dateVolumeData.length > 5) dateVolumeData = dateVolumeData.slice(0, 5);

  const statusCounts = statusCountsData.map((e) => ({
    name: e.status,
    value: e._count.status,
  }));

  const dateVolume = dateVolumeData
    .map((item, i) => ({
      date: item.application_date.toISOString().split("T")[0], // Convert DateTime to "YYYY-MM-DD" format
      applications: item._count.application_id, // Number of applications
    }))
    .reverse();

  return { statusCounts, dateVolume };
};

export const adminOptions = {
  dashboard: {
    component: Components.Dashboard,
    handler: dashboardHandler,
  },

  pages: {
    customPanel: {
      label: "Custom Panel",
      component: Components.CustomPanel,
    },
  },
  componentLoader,
  resources: [
    {
      resource: {
        model: getModelByName("Applicant"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("ApplicantEntity"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("Country"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("CountryGroup"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("CountryGroupMember"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("Employee"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("EntityMember"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("FreeVisaCountry"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("PastTravelDetails"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("RefreshTokens"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("User"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("UserCred"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("VisaCountryGroupFee"),
        client: prisma,
      },
    },
    {
      resource: {
        model: getModelByName("VisaType"),
        client: prisma,
      },
    },
  ],
  branding: {
    companyName: "Visa Application Admin",
    logo: "https://picsum.photos/200/300",
    softwareBrothers: false,
  },
};

// options: {
//   parent: { name: "Database", icon: "Database" },
//   properties: {
//     id: {
//       isVisible: {
//         edit: false,
//         show: false,
//         list: false,
//         filter: false,
//       }, // Hide ID as it's autogenerated
//     },
//     applicant: {
//       isTitle: true, // Sets this field as the title in the list view
//       type: "string", // Ensures a text field for the applicant's name
//     },
//     status: {
//       availableValues: [
//         { value: "Pending", label: "Pending" },
//         { value: "Approved", label: "Approved" },
//         { value: "Rejected", label: "Rejected" },
//       ], // Dropdown for status selection
//     },
//     createdAt: {
//       isVisible: { edit: false, show: true, list: true, filter: true }, // Hide from the form, show in other views
//     },
//     updatedAt: {
//       isVisible: { edit: false, show: true, list: true, filter: true }, // Hide from the form, show in other views
//     },
//   },
// },
