import AdminJS, { ComponentLoader, useTranslation } from "adminjs";
import AdminJSExpress from "@adminjs/express";
import express from "express";
import path, { dirname } from "path";
import { fileURLToPath } from "url";

import { Database, Resource, getModelByName } from "@adminjs/prisma";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
AdminJS.registerAdapter({ Database, Resource });

const PORT = 4000;

// Get the directory name of the current file
const __dirname = dirname(fileURLToPath(import.meta.url));

const start = async () => {
  const app = express();

  // Initialize Component Loader
  const componentLoader = new ComponentLoader();

  // Register your custom component
  const Components = {
    Dashboard: componentLoader.add("Dashboard", "./components/Dashboard"),
    CustomPanel: componentLoader.add("CustomPanel", "./components/CustomPanel"),
    // other custom components
  };
  const adminOptions = {
    dashboard: {
      component: Components.Dashboard,
    },

    pages: {
      customPanel: {
        label: "Custom Panel",
        component: Components.CustomPanel,
      },
    },
    componentLoader,
    resources: [
      {
        resource: {
          model: getModelByName("visa_application"),
          client: prisma,
        },
        options: {
          parent: { name: "Database", icon: "Database" },
          properties: {
            id: {
              isVisible: {
                edit: false,
                show: false,
                list: false,
                filter: false,
              }, // Hide ID as it's autogenerated
            },
            applicant: {
              isTitle: true, // Sets this field as the title in the list view
              type: "string", // Ensures a text field for the applicant's name
            },
            status: {
              availableValues: [
                { value: "Pending", label: "Pending" },
                { value: "Approved", label: "Approved" },
                { value: "Rejected", label: "Rejected" },
              ], // Dropdown for status selection
            },
            createdAt: {
              isVisible: { edit: false, show: true, list: true, filter: true }, // Hide from the form, show in other views
            },
            updatedAt: {
              isVisible: { edit: false, show: true, list: true, filter: true }, // Hide from the form, show in other views
            },
          },
        },
      },
    ],
    branding: {
      companyName: "Visa Application Admin",
      logo: "https://picsum.photos/200/300",
      softwareBrothers: false, // Path to your logo file
      // theme: {
      //   colors: {
      //     primary100: "#00ff00",
      //   },
      // },
    },
  };
  const admin = new AdminJS(adminOptions);

  admin.watch();

  // Serve static files (like your logo)
  app.use("/path/to/your", express.static(path.join(__dirname, "public")));

  const adminRouter = AdminJSExpress.buildRouter(admin);

  // Attach the AdminJS router
  app.use(admin.options.rootPath, adminRouter);

  app.listen(PORT, () => {
    console.log(
      `AdminJS started on http://localhost:${PORT}${admin.options.rootPath}`
    );
  });
};

start();
